create table if not exists public.prospects (
  id bigint generated by default as identity primary key,
  full_name text not null,
  country text,
  phone text,
  email text,
  facebook_profile text,
  interest_level text not null default 'Medium' check (interest_level in ('Low', 'Medium', 'High')),
  status text not null default 'New' check (status in ('New', 'Contacted', 'Presentation Sent', 'Follow-up Needed', 'Enrolled', 'Not Interested')),
  notes text,
  next_follow_up_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.prospects enable row level security;

create policy "Allow read access for authenticated users"
  on public.prospects
  for select
  using (auth.role() = 'authenticated');

create policy "Allow insert for authenticated users"
  on public.prospects
  for insert
  with check (auth.role() = 'authenticated');

create policy "Allow update for authenticated users"
  on public.prospects
  for update
  using (auth.role() = 'authenticated');

create policy "Allow delete for authenticated users"
  on public.prospects
  for delete
  using (auth.role() = 'authenticated');
